#!/bin/sh -e
# Copyright 2017 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ROOT_DIR=$1

ARCHIVE_DAYS=90

REQUEST=".request"
REQUEST_GO=".request.go"
RESPONSE=".response"
RESPONSE_GO=".response.go"

if [ "$ROOT_DIR" = "" ]; then
    echo "ERROR: Must provide dropbox root dir"
    echo "ERROR: syntax: <dropbox>"
    exit -1
fi

if [ -d $ROOT_DIR ]; then
    find -P $ROOT_DIR -mtime +$ARCHIVE_DAYS \( -name "*$REQUEST" -o -name "*$RESPONSE" -o -name "*$REQUEST_GO" -o -name "*$RESPONSE_GO" \) -exec rm -fv {} \;
else
    echo 'ERROR: provided directory does not exist'
    exit -1
fi

exit 0
