#!/bin/sh
# Copyright 2017 IBM Corp.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# 	http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "$1" = "" ]; then
  echo "Syntax: pullconfig <signframework-cfg base dir>"
  exit 1;
fi

BASEDIR=$1

if [ ! -e "$BASEDIR/cfgs/framework.cfg" ]; then
   echo "ERROR : $BASEDIR doesn't appear to have framework configuration files"
   exit 1;
fi

if [ ! -e "$PWD/framework.c" ]; then
   echo "ERROR : pullconfig must be run from framework directory"
   exit 1;
fi

cp -r $BASEDIR/cfgs/* .
